### ISSUE TITLE
Exception around socket list access

### ISSUE THREAD

**Issue by lb425** [lb425/LBudp#1]
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "./LBnucleus.py", line 104, in run
    self.socket=sockets[self.streamID]
AttributeError: 'inputHandler' object has no attribute 'streamID'

Firs seen in commit 1f3bc89a7cb12c785bf8ba37faec176e98d3c86a
https://github.com/lb425/LBudp/commit/1f3bc89a7cb12c785bf8ba37faec176e98d3c86a#diff-9e33862b3c2091fa4b4b0dd46be49108

**Comment by lb425** [comment]
Assignment of self.streamID variable (line 99) was commented out.
Resolved by uncommenting
